---
title: "Project In Statistics"
author: "Anders Gantzhorn Kristensen"
date: "2023-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(momentuHMM)
theme_set(theme_bw())
```

# Test

Check if everything works

```{r, include=FALSE}
eagleData <- readr::read_csv("GoldenEagle_FinalData_Dryad_FE.csv")
```

# Estimation
First assume that Step_length is Weibull distributed. The MLE of $k$ is the solution to
$$
0 = \frac{\sum_{i = 1}^N X_i^k\log(X_i)}{\sum_{i = 1}^N X_i^k} - \frac{1}{k} - \frac{1}{N}\sum_{i = 1}^N \log(X_i)
$$

whereas the MLE of $\lambda$ given $k$ is:
$$
\hat{\lambda} = \left(\frac{1}{N} \sum_{i = 1}^N X_i^k\right)^{\frac{1}{k}}
$$
Thus we can calculate the MLE assuming step-length has a Weibull distribtion
```{r}
k_hat <- uniroot(function(k) {sum(eagleData$Step_length^k * log(eagleData$Step_length)) / sum(eagleData$Step_length^k) - 1/k - mean(log(eagleData$Step_length))},
                    c(0.1, 10))$root
lambda_hat <- (mean(eagleData$Step_length^k_hat))^(1/k_hat)
```

We can simulate from this distribution and compare with the data

```{r}
simWei <- rweibull(50000, shape = k_hat, scale = lambda_hat)

tibble(x = c(simWei, eagleData$Step_length), type = rep(c("sim", "obs"), times = c(length(simWei), length(eagleData$Step_length)))) %>% ggplot(aes(x = x, color = type)) + geom_density()
```
Might not be the best fit to the Data, but it is a start.

